on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n evilacr -g evilacrae14-rg --location "Central US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n evilacr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n evilacr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n evilacr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: evilacr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.." -f  ".." -t evilacr.azurecr.io/kubeclust:${{ github.sha }}
        docker push evilacr.azurecr.io/kubeclust:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kubeclust_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubeclust50c4 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubeclust50c4`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubeclust50c4
        container-registry-url: evilacr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: kubeclustdockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: kubeclust50c4
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          evilacr.azurecr.io/kubeclust:${{ github.sha }}
        imagepullsecrets: |
          kubeclustdockerauth